{% set name = "tmmc-lnpy" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tmmc-lnpy-{{ version }}.tar.gz
  sha256: 3e608f7e6923d5e9e71af795e213f3474052144a8f8fa2504403951aa64192b5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=61.2
    - setuptools-scm >=7.0
    - pip
  run:
    - python >=3.8
    - numpy
    - xarray
    - scipy
    - scikit-image
    - joblib
    - bottleneck
    - tqdm
    - importlib-resources
    - module-utilities >=0.1
    - lazy_loader

test:
  imports:
    - lnpy
    - lnPi
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/usnistgov/tmmc-lnpy
  summary: Analysis of lnPi results from TMMC simulation
  description: |
    A package to analyze data from Transition Matrix Monte Carlo (tmmc)
    simulation. The main output from TMMC simulations, "lnPi", provides a
    means to calculate a host of thermodynamic properties. Moreover, if "lnPi"
    is calculated at a specific chemical potential, it can be reweighted to provide
    thermodynamic information at a different chemical potential.
  license: NIST-PD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - wpk-nist-gov
